package forge.game.card;

import forge.game.CardTraitBase;
import forge.game.Game;
import forge.game.player.Player;

import java.util.concurrent.ConcurrentHashMap;

/**
 * Forge Nova engine patch: direct answers for the card properties Forge tests most often.
 *
 * {@link CardProperty#cardHasProperty} is a chain of ~500 string comparisons; common properties sit deep in it
 * ("IsCommander" behind 252 tests, colors, types and "nonX" behind 262 tests, where the chain hands them to
 * {@link CardStateProperty}). Commander boards test these millions of times per game.
 *
 * Each answer below was derived mechanically (nova/bench/tools/ChainWalk.java, using javac's parser on the
 * decompiled Forge source): for the exact property string, every condition the chain evaluates before the
 * branch that handles it is a pure test of the property string (so no card state is read on the way), the
 * branch body is copied verbatim, and nothing but "return true" runs after it. The chain's prologue returns
 * false for phased-out cards unless the property starts with "phasedOut" (none of these do).
 * With -Dnova.verifyCaches=true every answer is compared with CardProperty.cardHasProperty.
 */
final class NovaProps {
    static final int UNKNOWN = -1;

    private NovaProps() {
    }

    /** 1 = has the property, 0 = hasn't, UNKNOWN = ask CardProperty. The card's game must not be null. */
    static int fast(Card card, String property, Player sourceController, Card source, CardTraitBase spellAbility) {
        switch (property) {
            case "Self": // CardProperty line 372
                return !card.isPhasedOut() && card.equals(source) ? 1 : 0;
            case "Other": // line 364
                return !card.isPhasedOut() && !card.equals(source) ? 1 : 0;
            case "IsCommander": // line 2069
                return !card.isPhasedOut() && card.isCommander() ? 1 : 0;
            case "YouOwn": // line 295
                return !card.isPhasedOut() && card.getOwner().equals(sourceController) ? 1 : 0;
            case "YouCtrl": // line 184 (controller = the card's change-zone LKI's controller, as in the prologue)
                return !card.isPhasedOut() && lkiController(card).equals(sourceController) ? 1 : 0;
            case "YouDontCtrl": // line 192
                return !card.isPhasedOut() && !lkiController(card).equals(sourceController) ? 1 : 0;
            case "OppCtrl": // line 196
                return !card.isPhasedOut() && lkiController(card).getOpponents().contains(sourceController) ? 1 : 0;
            case "token": // lines 1347 and 1351 ("token" contains no "Created")
                return !card.isPhasedOut() && (card.isToken() || card.isTokenCard()) ? 1 : 0;
            case "IsRemembered": // line 1952
                return !card.isPhasedOut() && source.isRemembered(card) ? 1 : 0;
            case "TopLibrary": { // line 2297, after 79 string tests (ChainWalk); "TopLibrary" skips the filter at 2298
                if (card.isPhasedOut()) {
                    return 0;
                }
                CardCollectionView cards = card.getOwner().getCardsIn(forge.game.zone.ZoneType.Library);
                return !cards.isEmpty() && card.equals(cards.get(0)) ? 1 : 0;
            }
            case "attacking": // lines 1462, 1466 and 1470 ("attacking" contains no "LKI")
                return !card.isPhasedOut() && card.getGame().getCombat() != null && card.isAttacking() ? 1 : 0;
            default:
                break;
        }
        if (!property.startsWith("phasedOut") && reachesStateFallback(property)) {
            // line 2238: if (!card.getCurrentState().hasProperty(property, ...)) return false; ... return true;
            return !card.isPhasedOut() && card.getCurrentState().hasProperty(property, sourceController, source, spellAbility) ? 1 : 0;
        }
        return UNKNOWN;
    }

    private static Player lkiController(Card card) {
        Game game = card.getGame();
        return game.getChangeZoneLKIInfo(card).getController();
    }

    private static final ConcurrentHashMap<String, Boolean> FALLBACK = new ConcurrentHashMap<>();

    /** true iff CardProperty's chain hands this property to CardState.hasProperty (memoized per string) */
    static boolean reachesStateFallback(String property) {
        Boolean b = FALLBACK.get(property);
        if (b == null) {
            b = walkToStateFallback(property);
            if (FALLBACK.size() > 20000) {
                FALLBACK.clear();
            }
            FALLBACK.put(property, b);
        }
        return b;
    }

    /**
     * Generated by ChainWalk (nova/bench/tools) from CardProperty.cardHasProperty of the decompiled
     * forge-gui-desktop-2.0.15-SNAPSHOT (build 2026-09-22): the 262 decisions on the way to the fallback at line
     * 2238, each of which must come out the same for the property to get there. A decision that would evaluate
     * anything but a string test of the property (c... returns 2) sends the property to CardProperty instead.
     */
    private static boolean walkToStateFallback(String property) {
      if (c56(property) != 0) return false; // line 56: (property.equals("noName"))
      if (c60(property) != 0) return false; // line 60: (property.startsWith("named"))
      if (c67(property) != 0) return false; // line 67: (property.equals("NamedCard"))
      if (c80(property) != 0) return false; // line 80: (property.equals("NamedByRememberedPlayer"))
      if (c89(property) != 0) return false; // line 89: (property.startsWith("BorderColor"))
      if (c93(property) != 0) return false; // line 93: (property.equals("Permanent"))
      if (c97(property) != 0) return false; // line 97: (property.equals("Historic"))
      if (c101(property) != 0) return false; // line 101: (property.startsWith("CardUID_"))
      if (c105(property) != 0) return false; // line 105: (property.startsWith("ChosenCard"))
      if (c115(property) != 0) return false; // line 115: (property.equals("nonChosenCard"))
      if (c119(property) != 0) return false; // line 119: (property.startsWith("ChosenMode"))
      if (c123(property) != 0) return false; // line 123: (property.equals("ChosenSector"))
      if (c127(property) != 0) return false; // line 127: (property.equals("DifferentSector"))
      if (c131(property) != 0) return false; // line 131: (property.equals("DoubleFaced"))
      if (c135(property) != 0) return false; // line 135: (property.equals("FrontSide"))
      if (c139(property) != 0) return false; // line 139: (property.equals("BackSide"))
      if (c143(property) != 0) return false; // line 143: (property.equals("CanTransform"))
      if (c147(property) != 0) return false; // line 147: (property.equals("Transformed"))
      if (c151(property) != 0) return false; // line 151: (property.equals("Flip"))
      if (c155(property) != 0) return false; // line 155: (property.equals("Split"))
      if (c159(property) != 0) return false; // line 159: (property.equals("AdventureCard"))
      if (c163(property) != 0) return false; // line 163: (property.equals("IsRingbearer"))
      if (c167(property) != 0) return false; // line 167: (property.equals("IsTriggerRemembered"))
      if (c183(property) != 0) return false; // line 183: (property.startsWith("YouCtrl"))
      if (c187(property) != 0) return false; // line 187: (property.startsWith("YourTeamCtrl"))
      if (c191(property) != 0) return false; // line 191: (property.startsWith("YouDontCtrl"))
      if (c195(property) != 0) return false; // line 195: (property.startsWith("OppCtrl"))
      if (c199(property) != 0) return false; // line 199: (property.startsWith("ChosenCtrl"))
      if (c203(property) != 0) return false; // line 203: (property.startsWith("DefenderCtrl"))
      if (c219(property) != 0) return false; // line 219: (property.startsWith("OppProtect"))
      if (c223(property) != 0) return false; // line 223: (property.startsWith("ProtectedBy"))
      if (c232(property) != 0) return false; // line 232: (property.equals("Defending"))
      if (c236(property) != 0) return false; // line 236: (property.startsWith("DefendingPlayer"))
      if (c245(property) != 0) return false; // line 245: (property.startsWith("EnchantedPlayer"))
      if (c255(property) != 0) return false; // line 255: (property.startsWith("EnchantedController"))
      if (c265(property) != 0) return false; // line 265: (property.startsWith("RememberedPlayer"))
      if (c277(property) != 0) return false; // line 277: (property.equals("targetedBy"))
      if (c286(property) != 0) return false; // line 286: (property.equals("TargetedPlayerCtrl"))
      if (c290(property) != 0) return false; // line 290: (property.startsWith("ActivePlayerCtrl"))
      if (c294(property) != 0) return false; // line 294: (property.startsWith("YouOwn"))
      if (c298(property) != 0) return false; // line 298: (property.startsWith("YouDontOwn"))
      if (c302(property) != 0) return false; // line 302: (property.startsWith("OppOwn"))
      if (c306(property) != 0) return false; // line 306: (property.equals("TargetedPlayerOwn"))
      if (c310(property) != 0) return false; // line 310: (property.startsWith("OwnedBy"))
      if (c318(property) != 0) return false; // line 318: (property.startsWith("ControlledBy"))
      if (c326(property) != 0) return false; // line 326: (property.startsWith("OwnerDoesntControl"))
      if (c330(property) != 0) return false; // line 330: (property.startsWith("ControllerControls"))
      if (c359(property) != 0) return false; // line 359: (property.startsWith("StrictlyOther"))
      if (c363(property) != 0) return false; // line 363: (property.startsWith("Other"))
      if (c367(property) != 0) return false; // line 367: (property.startsWith("StrictlySelf"))
      if (c371(property) != 0) return false; // line 371: (property.startsWith("Self"))
      if (c375(property) != 0) return false; // line 375: (property.startsWith("ExiledByYou"))
      if (c383(property) != 0) return false; // line 383: (property.startsWith("ExiledWithSourceLKI"))
      if (c407(property) != 0) return false; // line 407: (property.startsWith("ExiledWithSource"))
      if (c423(property) != 0) return false; // line 423: (property.equals("ExiledWithEffectSource"))
      if (c431(property) != 0) return false; // line 431: (property.equals("EncodedWithSource"))
      if (c435(property) != 0) return false; // line 435: (property.equals("EffectSource"))
      if (c443(property) != 0) return false; // line 443: (property.equals("CanBeSacrificedBy") && spellAbility instanceof SpellAbility)
      if (c447(property) != 0) return false; // line 447: (property.equals("Attached"))
      if (c451(property) != 0) return false; // line 451: (property.startsWith("AttachedTo"))
      if (c460(property) != 0) return false; // line 460: (property.equals("NameNotEnchantingEnchantedPlayer"))
      if (c465(property) != 0) return false; // line 465: (property.startsWith("EnchantedBy"))
      if (c496(property) != 0) return false; // line 496: (property.startsWith("Enchanted"))
      if (c500(property) != 0) return false; // line 500: (property.startsWith("CanEnchant"))
      if (c515(property) != 0) return false; // line 515: (property.startsWith("CanBeEnchantedBy"))
      if (c525(property) != 1) return false; // line 525: (!property.startsWith("EquippedBy") && !property.startsWith("AttachedBy"))
      if (c526(property) != 0) return false; // line 526: (property.startsWith("FortifiedBy"))
      if (c530(property) != 0) return false; // line 530: (property.startsWith("CanBeAttachedBy"))
      if (c534(property) != 0) return false; // line 534: (property.startsWith("CanBeTargetedBy"))
      if (c542(property) != 0) return false; // line 542: (property.startsWith("HauntedBy"))
      if (c546(property) != 0) return false; // line 546: (property.startsWith("notTributed"))
      if (c550(property) != 0) return false; // line 550: (property.startsWith("madness"))
      if (c554(property) != 0) return false; // line 554: (property.startsWith("Paired"))
      if (c562(property) != 0) return false; // line 562: (property.startsWith("Above"))
      if (c567(property) != 0) return false; // line 567: (property.startsWith("DirectlyAbove"))
      if (c572(property) != 0) return false; // line 572: (property.startsWith("TopGraveyardCreature"))
      if (c578(property) != 1) return false; // line 578: (!property.startsWith("TopGraveyard"))
      if (c579(property) != 0) return false; // line 579: (property.startsWith("BottomGraveyard"))
      if (c584(property) != 1) return false; // line 584: (!property.startsWith("TopLibrary") && !property.startsWith("BottomLibrary"))
      if (c585(property) != 0) return false; // line 585: (property.startsWith("Cloned"))
      if (c589(property) != 0) return false; // line 589: (property.startsWith("SharesCMCWith"))
      if (c599(property) != 0) return false; // line 599: (property.startsWith("SharesColorWith"))
      if (c660(property) != 0) return false; // line 660: (property.startsWith("MostProminentColor"))
      if (c672(property) != 0) return false; // line 672: (property.startsWith("MostProminentCreatureTypeInLibrary"))
      if (c680(property) != 0) return false; // line 680: (property.startsWith("sharesCreatureTypeWith"))
      if (c707(property) != 0) return false; // line 707: (property.startsWith("sharesCardTypeWith"))
      if (c748(property) != 0) return false; // line 748: (property.startsWith("sharesAllCardTypesWithOther"))
      if (c755(property) != 0) return false; // line 755: (property.startsWith("sharesLandTypeWith"))
      if (c760(property) != 0) return false; // line 760: (property.equals("sharesPermanentTypeWith"))
      if (c764(property) != 0) return false; // line 764: (property.equals("canProduceSameManaTypeWith"))
      if (c769(property) != 0) return false; // line 769: (property.startsWith("canProduceManaColor"))
      if (c781(property) != 0) return false; // line 781: (property.equals("canProduceMana"))
      if (c785(property) != 0) return false; // line 785: (property.startsWith("sameName"))
      if (c789(property) != 0) return false; // line 789: (property.startsWith("sharesNameWith"))
      if (c854(property) != 0) return false; // line 854: (property.startsWith("doesNotShareNameWith"))
      if (c885(property) != 0) return false; // line 885: (property.startsWith("sharesControllerWith"))
      if (c897(property) != 0) return false; // line 897: (property.startsWith("sharesOwnerWith"))
      if (c909(property) != 0) return false; // line 909: (property.startsWith("SecondSpellCastThisTurn"))
      if (c919(property) != 0) return false; // line 919: (property.equals("ThisTurnCast"))
      if (c929(property) != 0) return false; // line 929: (property.startsWith("EnteredUnder"))
      if (c942(property) != 0) return false; // line 942: (property.equals("EnteredSinceYourLastTurn"))
      if (c946(property) != 0) return false; // line 946: (property.startsWith("ThisTurnEnteredFrom"))
      if (c958(property) != 0) return false; // line 958: (property.startsWith("ThisTurnEntered"))
      if (c975(property) != 0) return false; // line 975: (property.equals("DiscardedThisTurn"))
      if (c983(property) != 0) return false; // line 983: (property.equals("surveilledThisTurn"))
      if (c991(property) != 0) return false; // line 991: (property.equals("milledThisTurn"))
      if (c999(property) != 0) return false; // line 999: (property.equals("hasABasicLandType"))
      if (c1003(property) != 0) return false; // line 1003: (property.equals("hasANonBasicLandType"))
      if (c1007(property) != 0) return false; // line 1007: (property.startsWith("hasKeyword"))
      if (c1011(property) != 0) return false; // line 1011: (property.startsWith("with"))
      if (c1019(property) != 0) return false; // line 1019: (property.startsWith("activated"))
      if (c1023(property) != 0) return false; // line 1023: (property.startsWith("tapped"))
      if (c1027(property) != 0) return false; // line 1027: (property.startsWith("untapped"))
      if (c1031(property) != 0) return false; // line 1031: (property.startsWith("faceDown"))
      if (c1035(property) != 0) return false; // line 1035: (property.startsWith("faceUp"))
      if (c1039(property) != 0) return false; // line 1039: (property.startsWith("turnedFaceUpThisTurn"))
      if (c1043(property) != 0) return false; // line 1043: (property.startsWith("phasedOut"))
      if (c1047(property) != 0) return false; // line 1047: (property.startsWith("phasedIn"))
      if (c1051(property) != 0) return false; // line 1051: (property.equals("manifested"))
      if (c1055(property) != 0) return false; // line 1055: (property.equals("cloaked"))
      if (c1059(property) != 0) return false; // line 1059: (property.startsWith("DrawnThisTurn"))
      if (c1063(property) != 0) return false; // line 1063: (property.startsWith("FoughtThisTurn"))
      if (c1067(property) != 0) return false; // line 1067: (property.startsWith("firstTurnControlled"))
      if (c1071(property) != 0) return false; // line 1071: (property.startsWith("startedTheTurnUntapped"))
      if (c1075(property) != 0) return false; // line 1075: (property.startsWith("cameUnderControlSinceLastUpkeep"))
      if (c1079(property) != 0) return false; // line 1079: (property.equals("attackedOrBlockedSinceYourLastUpkeep"))
      if (c1083(property) != 0) return false; // line 1083: (property.equals("blockedOrBeenBlockedSinceYourLastUpkeep"))
      if (c1087(property) != 0) return false; // line 1087: (property.startsWith("DamagedBy"))
      if (c1118(property) != 0) return false; // line 1118: (property.equals("isDamaged"))
      if (c1122(property) != 0) return false; // line 1122: (property.startsWith("Damaged"))
      if (c1135(property) != 0) return false; // line 1135: (property.startsWith("dealtCombatDamageThisCombat"))
      if (c1139(property) != 0) return false; // line 1139: (property.startsWith("dealtDamageToYouThisTurn"))
      if (c1143(property) != 0) return false; // line 1143: (property.startsWith("dealtDamageToOppThisTurn"))
      if (c1147(property) != 0) return false; // line 1147: (property.startsWith("dealtCombatDamageThisTurn"))
      if (c1151(property) != 0) return false; // line 1151: (property.startsWith("wasDealtDamageThisTurn"))
      if (c1155(property) != 0) return false; // line 1155: (property.equals("wasDealtNonCombatDamageThisTurn"))
      if (c1159(property) != 0) return false; // line 1159: (property.startsWith("wasDealtExcessDamageThisTurn"))
      if (c1163(property) != 0) return false; // line 1163: (property.startsWith("wasDealtDamageByThisGame"))
      if (c1173(property) != 0) return false; // line 1173: (property.startsWith("dealtDamageThisTurn"))
      if (c1178(property) != 0) return false; // line 1178: (property.startsWith("dealtDamagetoAny"))
      if (c1182(property) != 0) return false; // line 1182: (property.startsWith("dealtCombatDamagetoAny"))
      if (c1186(property) != 0) return false; // line 1186: (property.startsWith("attackedThisTurn"))
      if (c1190(property) != 0) return false; // line 1190: (property.startsWith("attackedBattleThisTurn"))
      if (c1194(property) != 0) return false; // line 1194: (property.startsWith("attackedYouThisTurn"))
      if (c1199(property) != 0) return false; // line 1199: (property.startsWith("attackedLastTurn"))
      if (c1203(property) != 0) return false; // line 1203: (property.startsWith("blockedThisTurn"))
      if (c1207(property) != 0) return false; // line 1207: (property.startsWith("notExertedThisTurn"))
      if (c1211(property) != 0) return false; // line 1211: (property.startsWith("gotBlockedThisTurn"))
      if (c1215(property) != 0) return false; // line 1215: (property.startsWith("greatestPower"))
      if (c1230(property) != 0) return false; // line 1230: (property.startsWith("yardGreatestPower"))
      if (c1236(property) != 0) return false; // line 1236: (property.startsWith("leastPower"))
      if (c1251(property) != 0) return false; // line 1251: (property.startsWith("leastToughness"))
      if (c1266(property) != 0) return false; // line 1266: (property.startsWith("greatestCMC_"))
      if (c1286(property) != 0) return false; // line 1286: (property.startsWith("greatestRememberedCMC"))
      if (c1303(property) != 0) return false; // line 1303: (property.startsWith("lowestRememberedCMC"))
      if (c1320(property) != 0) return false; // line 1320: (property.startsWith("lowestCMC"))
      if (c1326(property) != 0) return false; // line 1326: (property.startsWith("enchanted"))
      if (c1330(property) != 0) return false; // line 1330: (property.startsWith("enchanting"))
      if (c1334(property) != 0) return false; // line 1334: (property.startsWith("equipped"))
      if (c1338(property) != 0) return false; // line 1338: (property.startsWith("equipping"))
      if (c1342(property) != 0) return false; // line 1342: (property.startsWith("modified"))
      if (c1346(property) != 0) return false; // line 1346: (property.startsWith("token"))
      if (c1354(property) != 0) return false; // line 1354: (property.startsWith("copiedSpell"))
      if (c1358(property) != 0) return false; // line 1358: (property.startsWith("hasXCost"))
      if (c1363(property) != 0) return false; // line 1363: (property.startsWith("suspended"))
      if (c1367(property) != 0) return false; // line 1367: (property.startsWith("delved"))
      if (c1371(property) != 0) return false; // line 1371: (property.startsWith("convoked"))
      if (c1375(property) != 0) return false; // line 1375: (property.startsWith("exploited"))
      if (c1379(property) != 0) return false; // line 1379: (property.startsWith("equalPT"))
      if (c1383(property) != 0) return false; // line 1383: (property.equals("powerGTtoughness"))
      if (c1387(property) != 0) return false; // line 1387: (property.equals("powerGTbasePower"))
      if (c1391(property) != 0) return false; // line 1391: (property.equals("powerNOTbasePower"))
      if (c1395(property) != 0) return false; // line 1395: (property.equals("powerLTtoughness"))
      if (c1399(property) != 0) return false; // line 1399: (property.equals("cmcEven"))
      if (c1403(property) != 0) return false; // line 1403: (property.equals("cmcOdd"))
      if (c1407(property) != 0) return false; // line 1407: (property.equals("powerEven"))
      if (c1411(property) != 0) return false; // line 1411: (property.equals("powerOdd"))
      if (c1415(property) != 0) return false; // line 1415: (property.equals("cmcChosenEvenOdd"))
      if (c1423(property) != 0) return false; // line 1423: (property.equals("cmcNotChosenEvenOdd"))
      if (c1431(property) != 1) return false; // line 1431: (!property.startsWith("power") && !property.startsWith("toughness") && !property.startsWith("cmc") && !property.startsWith("totalPT") && !property.sta...
      if (c1432(property) != 0) return false; // line 1432: (property.startsWith("ManaCost"))
      if (c1441(property) != 0) return false; // line 1441: (property.equals("HasCounters"))
      if (c1445(property) != 0) return false; // line 1445: (property.startsWith("counters"))
      if (c1461(property) != 0) return false; // line 1461: (property.startsWith("attacking"))
      if (c1522(property) != 0) return false; // line 1522: (property.startsWith("enlistedThisCombat"))
      if (c1526(property) != 0) return false; // line 1526: (property.startsWith("attackedThisCombat"))
      if (c1537(property) != 0) return false; // line 1537: (property.equals("blockedThisCombat"))
      if (c1541(property) != 0) return false; // line 1541: (property.equals("attackedBySourceThisCombat"))
      if (c1550(property) != 0) return false; // line 1550: (property.startsWith("blocking"))
      if (c1583(property) != 0) return false; // line 1583: (property.startsWith("sharesBlockingAssignmentWith"))
      if (c1596(property) != 0) return false; // line 1596: (property.equals("blocked"))
      if (c1600(property) != 0) return false; // line 1600: (property.startsWith("blockedBySourceThisTurn"))
      if (c1604(property) != 0) return false; // line 1604: (property.startsWith("blockedBySourceLKI"))
      if (c1608(property) != 0) return false; // line 1608: (property.startsWith("blockedBySource"))
      if (c1612(property) != 0) return false; // line 1612: (property.startsWith("blockedThisTurn"))
      if (c1616(property) != 0) return false; // line 1616: (property.startsWith("blockedByThisTurn"))
      if (c1620(property) != 0) return false; // line 1620: (property.startsWith("blockedValidThisTurn "))
      if (c1640(property) != 0) return false; // line 1640: (property.startsWith("blockedByValidThisTurn "))
      if (c1660(property) != 0) return false; // line 1660: (property.startsWith("isBlockedByRemembered"))
      if (c1674(property) != 0) return false; // line 1674: (property.startsWith("blockedRemembered"))
      if (c1687(property) != 0) return false; // line 1687: (property.startsWith("blockedByRemembered"))
      if (c1700(property) != 0) return false; // line 1700: (property.startsWith("unblocked"))
      if (c1704(property) != 0) return false; // line 1704: (property.equals("attackersBandedWith"))
      if (c1713(property) != 0) return false; // line 1713: (property.equals("hadToAttackThisCombat"))
      if (c1719(property) != 0) return false; // line 1719: (property.equals("couldAttackButNotAttacking"))
      if (c1727(property) != 0) return false; // line 1727: (property.equals("linkedCastSA"))
      if (c1735(property) != 0) return false; // line 1735: (property.startsWith("kicked"))
      if (c1755(property) != 0) return false; // line 1755: (property.equals("bargained"))
      if (c1767(property) != 0) return false; // line 1767: (property.equals("surged"))
      if (c1779(property) != 0) return false; // line 1779: (property.equals("blitzed"))
      if (c1791(property) != 0) return false; // line 1791: (property.equals("dashed"))
      if (c1803(property) != 0) return false; // line 1803: (property.equals("escaped"))
      if (c1811(property) != 0) return false; // line 1811: (property.equals("evoked"))
      if (c1823(property) != 0) return false; // line 1823: (property.equals("PromisedGift"))
      if (c1831(property) != 0) return false; // line 1831: (property.equals("Teamwork"))
      if (c1839(property) != 0) return false; // line 1839: (property.equals("impended"))
      if (c1851(property) != 0) return false; // line 1851: (property.equals("prowled"))
      if (c1863(property) != 0) return false; // line 1863: (property.equals("spectacle"))
      if (c1875(property) != 0) return false; // line 1875: (property.equals("sneaked"))
      if (c1887(property) != 0) return false; // line 1887: (property.equals("foretold"))
      if (c1891(property) != 0) return false; // line 1891: (property.equals("warped"))
      if (c1895(property) != 0) return false; // line 1895: (property.equals("webSlinged"))
      if (c1899(property) != 0) return false; // line 1899: (property.equals("CrewedThisTurn"))
      if (c1903(property) != 0) return false; // line 1903: (property.equals("CrewedBySourceThisTurn"))
      if (c1907(property) != 0) return false; // line 1907: (property.equals("HasDevoured"))
      if (c1911(property) != 0) return false; // line 1911: (property.equals("harnessed"))
      if (c1915(property) != 0) return false; // line 1915: (property.equals("IsMonstrous"))
      if (c1919(property) != 0) return false; // line 1919: (property.equals("IsUnearthed"))
      if (c1923(property) != 0) return false; // line 1923: (property.equals("IsRenowned"))
      if (c1927(property) != 0) return false; // line 1927: (property.equals("IsSolved"))
      if (c1931(property) != 0) return false; // line 1931: (property.equals("IsSaddled"))
      if (c1935(property) != 0) return false; // line 1935: (property.equals("SaddledThisTurn"))
      if (c1939(property) != 0) return false; // line 1939: (property.equals("VisitedThisTurn"))
      if (c1943(property) != 0) return false; // line 1943: (property.equals("IsSuspected"))
      if (c1947(property) != 0) return false; // line 1947: (property.equals("IsPrepared"))
      if (c1951(property) != 0) return false; // line 1951: (property.equals("IsRemembered"))
      if (c1955(property) != 0) return false; // line 1955: (property.equals("IsImprinted"))
      if (c1959(property) != 0) return false; // line 1959: (property.equals("IsGoaded"))
      if (c1963(property) != 0) return false; // line 1963: (property.equals("FullyUnlocked"))
      if (c1967(property) != 0) return false; // line 1967: (property.startsWith("canReceiveCounters"))
      if (c1971(property) != 0) return false; // line 1971: (property.equals("canBeTurnedFaceUp"))
      if (c1975(property) != 0) return false; // line 1975: (property.equals("canBeBeamedUp"))
      if (c1979(property) != 0) return false; // line 1979: (property.equals("NoAbilities"))
      if (c1983(property) != 0) return false; // line 1983: (property.equals("castKeyword"))
      if (c1996(property) != 0) return false; // line 1996: (property.equals("CastSaSource"))
      if (c2005(property) != 0) return false; // line 2005: (property.startsWith("CastSa"))
      if (c2015(property) != 0) return false; // line 2015: (property.startsWith("wasCastFrom"))
      if (c2037(property) != 0) return false; // line 2037: (property.startsWith("wasCast"))
      if (c2045(property) != 0) return false; // line 2045: (property.startsWith("set"))
      if (c2055(property) != 0) return false; // line 2055: (property.startsWith("inZone"))
      if (c2062(property) != 0) return false; // line 2062: (property.startsWith("inRealZone"))
      if (c2068(property) != 0) return false; // line 2068: (property.equals("IsCommander"))
      if (c2073(property) != 0) return false; // line 2073: (property.startsWith("NotedFor"))
      if (c2089(property) != 0) return false; // line 2089: (property.equals("NotedColor"))
      if (c2098(property) != 0) return false; // line 2098: (property.equals("NotedNameNobleBanneret"))
      if (c2108(property) != 0) return false; // line 2108: (property.equals("NotedNameAetherSearcher"))
      if (c2118(property) != 0) return false; // line 2118: (property.equals("NotedNameSmugglerCaptain"))
      if (c2128(property) != 0) return false; // line 2128: (property.equals("NotedGuessPhantasm"))
      if (c2133(property) != 0) return false; // line 2133: (property.equals("NotedTypes"))
      if (c2145(property) != 0) return false; // line 2145: (property.startsWith("Triggered"))
      if (c2165(property) != 0) return false; // line 2165: (property.startsWith("NotDefined"))
      if (c2171(property) != 0) return false; // line 2171: (property.equals("CanPayManaCost"))
      return true;
    }

    private static int c56(String property) { // line 56
        int v0 = (property.equals("noName")) ? 1 : 0;
        return v0;
    }

    private static int c60(String property) { // line 60
        int v0 = (property.startsWith("named")) ? 1 : 0;
        return v0;
    }

    private static int c67(String property) { // line 67
        int v0 = (property.equals("NamedCard")) ? 1 : 0;
        return v0;
    }

    private static int c80(String property) { // line 80
        int v0 = (property.equals("NamedByRememberedPlayer")) ? 1 : 0;
        return v0;
    }

    private static int c89(String property) { // line 89
        int v0 = (property.startsWith("BorderColor")) ? 1 : 0;
        return v0;
    }

    private static int c93(String property) { // line 93
        int v0 = (property.equals("Permanent")) ? 1 : 0;
        return v0;
    }

    private static int c97(String property) { // line 97
        int v0 = (property.equals("Historic")) ? 1 : 0;
        return v0;
    }

    private static int c101(String property) { // line 101
        int v0 = (property.startsWith("CardUID_")) ? 1 : 0;
        return v0;
    }

    private static int c105(String property) { // line 105
        int v0 = (property.startsWith("ChosenCard")) ? 1 : 0;
        return v0;
    }

    private static int c115(String property) { // line 115
        int v0 = (property.equals("nonChosenCard")) ? 1 : 0;
        return v0;
    }

    private static int c119(String property) { // line 119
        int v0 = (property.startsWith("ChosenMode")) ? 1 : 0;
        return v0;
    }

    private static int c123(String property) { // line 123
        int v0 = (property.equals("ChosenSector")) ? 1 : 0;
        return v0;
    }

    private static int c127(String property) { // line 127
        int v0 = (property.equals("DifferentSector")) ? 1 : 0;
        return v0;
    }

    private static int c131(String property) { // line 131
        int v0 = (property.equals("DoubleFaced")) ? 1 : 0;
        return v0;
    }

    private static int c135(String property) { // line 135
        int v0 = (property.equals("FrontSide")) ? 1 : 0;
        return v0;
    }

    private static int c139(String property) { // line 139
        int v0 = (property.equals("BackSide")) ? 1 : 0;
        return v0;
    }

    private static int c143(String property) { // line 143
        int v0 = (property.equals("CanTransform")) ? 1 : 0;
        return v0;
    }

    private static int c147(String property) { // line 147
        int v0 = (property.equals("Transformed")) ? 1 : 0;
        return v0;
    }

    private static int c151(String property) { // line 151
        int v0 = (property.equals("Flip")) ? 1 : 0;
        return v0;
    }

    private static int c155(String property) { // line 155
        int v0 = (property.equals("Split")) ? 1 : 0;
        return v0;
    }

    private static int c159(String property) { // line 159
        int v0 = (property.equals("AdventureCard")) ? 1 : 0;
        return v0;
    }

    private static int c163(String property) { // line 163
        int v0 = (property.equals("IsRingbearer")) ? 1 : 0;
        return v0;
    }

    private static int c167(String property) { // line 167
        int v0 = (property.equals("IsTriggerRemembered")) ? 1 : 0;
        return v0;
    }

    private static int c183(String property) { // line 183
        int v0 = (property.startsWith("YouCtrl")) ? 1 : 0;
        return v0;
    }

    private static int c187(String property) { // line 187
        int v0 = (property.startsWith("YourTeamCtrl")) ? 1 : 0;
        return v0;
    }

    private static int c191(String property) { // line 191
        int v0 = (property.startsWith("YouDontCtrl")) ? 1 : 0;
        return v0;
    }

    private static int c195(String property) { // line 195
        int v0 = (property.startsWith("OppCtrl")) ? 1 : 0;
        return v0;
    }

    private static int c199(String property) { // line 199
        int v0 = (property.startsWith("ChosenCtrl")) ? 1 : 0;
        return v0;
    }

    private static int c203(String property) { // line 203
        int v0 = (property.startsWith("DefenderCtrl")) ? 1 : 0;
        return v0;
    }

    private static int c219(String property) { // line 219
        int v0 = (property.startsWith("OppProtect")) ? 1 : 0;
        return v0;
    }

    private static int c223(String property) { // line 223
        int v0 = (property.startsWith("ProtectedBy")) ? 1 : 0;
        return v0;
    }

    private static int c232(String property) { // line 232
        int v0 = (property.equals("Defending")) ? 1 : 0;
        return v0;
    }

    private static int c236(String property) { // line 236
        int v0 = (property.startsWith("DefendingPlayer")) ? 1 : 0;
        return v0;
    }

    private static int c245(String property) { // line 245
        int v0 = (property.startsWith("EnchantedPlayer")) ? 1 : 0;
        return v0;
    }

    private static int c255(String property) { // line 255
        int v0 = (property.startsWith("EnchantedController")) ? 1 : 0;
        return v0;
    }

    private static int c265(String property) { // line 265
        int v0 = (property.startsWith("RememberedPlayer")) ? 1 : 0;
        return v0;
    }

    private static int c277(String property) { // line 277
        int v0 = (property.equals("targetedBy")) ? 1 : 0;
        return v0;
    }

    private static int c286(String property) { // line 286
        int v0 = (property.equals("TargetedPlayerCtrl")) ? 1 : 0;
        return v0;
    }

    private static int c290(String property) { // line 290
        int v0 = (property.startsWith("ActivePlayerCtrl")) ? 1 : 0;
        return v0;
    }

    private static int c294(String property) { // line 294
        int v0 = (property.startsWith("YouOwn")) ? 1 : 0;
        return v0;
    }

    private static int c298(String property) { // line 298
        int v0 = (property.startsWith("YouDontOwn")) ? 1 : 0;
        return v0;
    }

    private static int c302(String property) { // line 302
        int v0 = (property.startsWith("OppOwn")) ? 1 : 0;
        return v0;
    }

    private static int c306(String property) { // line 306
        int v0 = (property.equals("TargetedPlayerOwn")) ? 1 : 0;
        return v0;
    }

    private static int c310(String property) { // line 310
        int v0 = (property.startsWith("OwnedBy")) ? 1 : 0;
        return v0;
    }

    private static int c318(String property) { // line 318
        int v0 = (property.startsWith("ControlledBy")) ? 1 : 0;
        return v0;
    }

    private static int c326(String property) { // line 326
        int v0 = (property.startsWith("OwnerDoesntControl")) ? 1 : 0;
        return v0;
    }

    private static int c330(String property) { // line 330
        int v0 = (property.startsWith("ControllerControls")) ? 1 : 0;
        return v0;
    }

    private static int c359(String property) { // line 359
        int v0 = (property.startsWith("StrictlyOther")) ? 1 : 0;
        return v0;
    }

    private static int c363(String property) { // line 363
        int v0 = (property.startsWith("Other")) ? 1 : 0;
        return v0;
    }

    private static int c367(String property) { // line 367
        int v0 = (property.startsWith("StrictlySelf")) ? 1 : 0;
        return v0;
    }

    private static int c371(String property) { // line 371
        int v0 = (property.startsWith("Self")) ? 1 : 0;
        return v0;
    }

    private static int c375(String property) { // line 375
        int v0 = (property.startsWith("ExiledByYou")) ? 1 : 0;
        return v0;
    }

    private static int c383(String property) { // line 383
        int v0 = (property.startsWith("ExiledWithSourceLKI")) ? 1 : 0;
        return v0;
    }

    private static int c407(String property) { // line 407
        int v0 = (property.startsWith("ExiledWithSource")) ? 1 : 0;
        return v0;
    }

    private static int c423(String property) { // line 423
        int v0 = (property.equals("ExiledWithEffectSource")) ? 1 : 0;
        return v0;
    }

    private static int c431(String property) { // line 431
        int v0 = (property.equals("EncodedWithSource")) ? 1 : 0;
        return v0;
    }

    private static int c435(String property) { // line 435
        int v0 = (property.equals("EffectSource")) ? 1 : 0;
        return v0;
    }

    private static int c443(String property) { // line 443
        int v1 = (property.equals("CanBeSacrificedBy")) ? 1 : 0;
        int v0 = v1;
        if (v1 == 1) {
            int v2 = 2; // not a pure test of the property: spellAbility instanceof SpellAbility
            v0 = v2;
        }
        return v0;
    }

    private static int c447(String property) { // line 447
        int v0 = (property.equals("Attached")) ? 1 : 0;
        return v0;
    }

    private static int c451(String property) { // line 451
        int v0 = (property.startsWith("AttachedTo")) ? 1 : 0;
        return v0;
    }

    private static int c460(String property) { // line 460
        int v0 = (property.equals("NameNotEnchantingEnchantedPlayer")) ? 1 : 0;
        return v0;
    }

    private static int c465(String property) { // line 465
        int v0 = (property.startsWith("EnchantedBy")) ? 1 : 0;
        return v0;
    }

    private static int c496(String property) { // line 496
        int v0 = (property.startsWith("Enchanted")) ? 1 : 0;
        return v0;
    }

    private static int c500(String property) { // line 500
        int v0 = (property.startsWith("CanEnchant")) ? 1 : 0;
        return v0;
    }

    private static int c515(String property) { // line 515
        int v0 = (property.startsWith("CanBeEnchantedBy")) ? 1 : 0;
        return v0;
    }

    private static int c525(String property) { // line 525
        int v2 = (property.startsWith("EquippedBy")) ? 1 : 0;
        int v1 = v2 == 2 ? 2 : 1 - v2;
        int v0 = v1;
        if (v1 == 1) {
            int v4 = (property.startsWith("AttachedBy")) ? 1 : 0;
            int v3 = v4 == 2 ? 2 : 1 - v4;
            v0 = v3;
        }
        return v0;
    }

    private static int c526(String property) { // line 526
        int v0 = (property.startsWith("FortifiedBy")) ? 1 : 0;
        return v0;
    }

    private static int c530(String property) { // line 530
        int v0 = (property.startsWith("CanBeAttachedBy")) ? 1 : 0;
        return v0;
    }

    private static int c534(String property) { // line 534
        int v0 = (property.startsWith("CanBeTargetedBy")) ? 1 : 0;
        return v0;
    }

    private static int c542(String property) { // line 542
        int v0 = (property.startsWith("HauntedBy")) ? 1 : 0;
        return v0;
    }

    private static int c546(String property) { // line 546
        int v0 = (property.startsWith("notTributed")) ? 1 : 0;
        return v0;
    }

    private static int c550(String property) { // line 550
        int v0 = (property.startsWith("madness")) ? 1 : 0;
        return v0;
    }

    private static int c554(String property) { // line 554
        int v0 = (property.startsWith("Paired")) ? 1 : 0;
        return v0;
    }

    private static int c562(String property) { // line 562
        int v0 = (property.startsWith("Above")) ? 1 : 0;
        return v0;
    }

    private static int c567(String property) { // line 567
        int v0 = (property.startsWith("DirectlyAbove")) ? 1 : 0;
        return v0;
    }

    private static int c572(String property) { // line 572
        int v0 = (property.startsWith("TopGraveyardCreature")) ? 1 : 0;
        return v0;
    }

    private static int c578(String property) { // line 578
        int v1 = (property.startsWith("TopGraveyard")) ? 1 : 0;
        int v0 = v1 == 2 ? 2 : 1 - v1;
        return v0;
    }

    private static int c579(String property) { // line 579
        int v0 = (property.startsWith("BottomGraveyard")) ? 1 : 0;
        return v0;
    }

    private static int c584(String property) { // line 584
        int v2 = (property.startsWith("TopLibrary")) ? 1 : 0;
        int v1 = v2 == 2 ? 2 : 1 - v2;
        int v0 = v1;
        if (v1 == 1) {
            int v4 = (property.startsWith("BottomLibrary")) ? 1 : 0;
            int v3 = v4 == 2 ? 2 : 1 - v4;
            v0 = v3;
        }
        return v0;
    }

    private static int c585(String property) { // line 585
        int v0 = (property.startsWith("Cloned")) ? 1 : 0;
        return v0;
    }

    private static int c589(String property) { // line 589
        int v0 = (property.startsWith("SharesCMCWith")) ? 1 : 0;
        return v0;
    }

    private static int c599(String property) { // line 599
        int v0 = (property.startsWith("SharesColorWith")) ? 1 : 0;
        return v0;
    }

    private static int c660(String property) { // line 660
        int v0 = (property.startsWith("MostProminentColor")) ? 1 : 0;
        return v0;
    }

    private static int c672(String property) { // line 672
        int v0 = (property.startsWith("MostProminentCreatureTypeInLibrary")) ? 1 : 0;
        return v0;
    }

    private static int c680(String property) { // line 680
        int v0 = (property.startsWith("sharesCreatureTypeWith")) ? 1 : 0;
        return v0;
    }

    private static int c707(String property) { // line 707
        int v0 = (property.startsWith("sharesCardTypeWith")) ? 1 : 0;
        return v0;
    }

    private static int c748(String property) { // line 748
        int v0 = (property.startsWith("sharesAllCardTypesWithOther")) ? 1 : 0;
        return v0;
    }

    private static int c755(String property) { // line 755
        int v0 = (property.startsWith("sharesLandTypeWith")) ? 1 : 0;
        return v0;
    }

    private static int c760(String property) { // line 760
        int v0 = (property.equals("sharesPermanentTypeWith")) ? 1 : 0;
        return v0;
    }

    private static int c764(String property) { // line 764
        int v0 = (property.equals("canProduceSameManaTypeWith")) ? 1 : 0;
        return v0;
    }

    private static int c769(String property) { // line 769
        int v0 = (property.startsWith("canProduceManaColor")) ? 1 : 0;
        return v0;
    }

    private static int c781(String property) { // line 781
        int v0 = (property.equals("canProduceMana")) ? 1 : 0;
        return v0;
    }

    private static int c785(String property) { // line 785
        int v0 = (property.startsWith("sameName")) ? 1 : 0;
        return v0;
    }

    private static int c789(String property) { // line 789
        int v0 = (property.startsWith("sharesNameWith")) ? 1 : 0;
        return v0;
    }

    private static int c854(String property) { // line 854
        int v0 = (property.startsWith("doesNotShareNameWith")) ? 1 : 0;
        return v0;
    }

    private static int c885(String property) { // line 885
        int v0 = (property.startsWith("sharesControllerWith")) ? 1 : 0;
        return v0;
    }

    private static int c897(String property) { // line 897
        int v0 = (property.startsWith("sharesOwnerWith")) ? 1 : 0;
        return v0;
    }

    private static int c909(String property) { // line 909
        int v0 = (property.startsWith("SecondSpellCastThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c919(String property) { // line 919
        int v0 = (property.equals("ThisTurnCast")) ? 1 : 0;
        return v0;
    }

    private static int c929(String property) { // line 929
        int v0 = (property.startsWith("EnteredUnder")) ? 1 : 0;
        return v0;
    }

    private static int c942(String property) { // line 942
        int v0 = (property.equals("EnteredSinceYourLastTurn")) ? 1 : 0;
        return v0;
    }

    private static int c946(String property) { // line 946
        int v0 = (property.startsWith("ThisTurnEnteredFrom")) ? 1 : 0;
        return v0;
    }

    private static int c958(String property) { // line 958
        int v0 = (property.startsWith("ThisTurnEntered")) ? 1 : 0;
        return v0;
    }

    private static int c975(String property) { // line 975
        int v0 = (property.equals("DiscardedThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c983(String property) { // line 983
        int v0 = (property.equals("surveilledThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c991(String property) { // line 991
        int v0 = (property.equals("milledThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c999(String property) { // line 999
        int v0 = (property.equals("hasABasicLandType")) ? 1 : 0;
        return v0;
    }

    private static int c1003(String property) { // line 1003
        int v0 = (property.equals("hasANonBasicLandType")) ? 1 : 0;
        return v0;
    }

    private static int c1007(String property) { // line 1007
        int v0 = (property.startsWith("hasKeyword")) ? 1 : 0;
        return v0;
    }

    private static int c1011(String property) { // line 1011
        int v0 = (property.startsWith("with")) ? 1 : 0;
        return v0;
    }

    private static int c1019(String property) { // line 1019
        int v0 = (property.startsWith("activated")) ? 1 : 0;
        return v0;
    }

    private static int c1023(String property) { // line 1023
        int v0 = (property.startsWith("tapped")) ? 1 : 0;
        return v0;
    }

    private static int c1027(String property) { // line 1027
        int v0 = (property.startsWith("untapped")) ? 1 : 0;
        return v0;
    }

    private static int c1031(String property) { // line 1031
        int v0 = (property.startsWith("faceDown")) ? 1 : 0;
        return v0;
    }

    private static int c1035(String property) { // line 1035
        int v0 = (property.startsWith("faceUp")) ? 1 : 0;
        return v0;
    }

    private static int c1039(String property) { // line 1039
        int v0 = (property.startsWith("turnedFaceUpThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1043(String property) { // line 1043
        int v0 = (property.startsWith("phasedOut")) ? 1 : 0;
        return v0;
    }

    private static int c1047(String property) { // line 1047
        int v0 = (property.startsWith("phasedIn")) ? 1 : 0;
        return v0;
    }

    private static int c1051(String property) { // line 1051
        int v0 = (property.equals("manifested")) ? 1 : 0;
        return v0;
    }

    private static int c1055(String property) { // line 1055
        int v0 = (property.equals("cloaked")) ? 1 : 0;
        return v0;
    }

    private static int c1059(String property) { // line 1059
        int v0 = (property.startsWith("DrawnThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1063(String property) { // line 1063
        int v0 = (property.startsWith("FoughtThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1067(String property) { // line 1067
        int v0 = (property.startsWith("firstTurnControlled")) ? 1 : 0;
        return v0;
    }

    private static int c1071(String property) { // line 1071
        int v0 = (property.startsWith("startedTheTurnUntapped")) ? 1 : 0;
        return v0;
    }

    private static int c1075(String property) { // line 1075
        int v0 = (property.startsWith("cameUnderControlSinceLastUpkeep")) ? 1 : 0;
        return v0;
    }

    private static int c1079(String property) { // line 1079
        int v0 = (property.equals("attackedOrBlockedSinceYourLastUpkeep")) ? 1 : 0;
        return v0;
    }

    private static int c1083(String property) { // line 1083
        int v0 = (property.equals("blockedOrBeenBlockedSinceYourLastUpkeep")) ? 1 : 0;
        return v0;
    }

    private static int c1087(String property) { // line 1087
        int v0 = (property.startsWith("DamagedBy")) ? 1 : 0;
        return v0;
    }

    private static int c1118(String property) { // line 1118
        int v0 = (property.equals("isDamaged")) ? 1 : 0;
        return v0;
    }

    private static int c1122(String property) { // line 1122
        int v0 = (property.startsWith("Damaged")) ? 1 : 0;
        return v0;
    }

    private static int c1135(String property) { // line 1135
        int v0 = (property.startsWith("dealtCombatDamageThisCombat")) ? 1 : 0;
        return v0;
    }

    private static int c1139(String property) { // line 1139
        int v0 = (property.startsWith("dealtDamageToYouThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1143(String property) { // line 1143
        int v0 = (property.startsWith("dealtDamageToOppThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1147(String property) { // line 1147
        int v0 = (property.startsWith("dealtCombatDamageThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1151(String property) { // line 1151
        int v0 = (property.startsWith("wasDealtDamageThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1155(String property) { // line 1155
        int v0 = (property.equals("wasDealtNonCombatDamageThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1159(String property) { // line 1159
        int v0 = (property.startsWith("wasDealtExcessDamageThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1163(String property) { // line 1163
        int v0 = (property.startsWith("wasDealtDamageByThisGame")) ? 1 : 0;
        return v0;
    }

    private static int c1173(String property) { // line 1173
        int v0 = (property.startsWith("dealtDamageThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1178(String property) { // line 1178
        int v0 = (property.startsWith("dealtDamagetoAny")) ? 1 : 0;
        return v0;
    }

    private static int c1182(String property) { // line 1182
        int v0 = (property.startsWith("dealtCombatDamagetoAny")) ? 1 : 0;
        return v0;
    }

    private static int c1186(String property) { // line 1186
        int v0 = (property.startsWith("attackedThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1190(String property) { // line 1190
        int v0 = (property.startsWith("attackedBattleThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1194(String property) { // line 1194
        int v0 = (property.startsWith("attackedYouThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1199(String property) { // line 1199
        int v0 = (property.startsWith("attackedLastTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1203(String property) { // line 1203
        int v0 = (property.startsWith("blockedThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1207(String property) { // line 1207
        int v0 = (property.startsWith("notExertedThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1211(String property) { // line 1211
        int v0 = (property.startsWith("gotBlockedThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1215(String property) { // line 1215
        int v0 = (property.startsWith("greatestPower")) ? 1 : 0;
        return v0;
    }

    private static int c1230(String property) { // line 1230
        int v0 = (property.startsWith("yardGreatestPower")) ? 1 : 0;
        return v0;
    }

    private static int c1236(String property) { // line 1236
        int v0 = (property.startsWith("leastPower")) ? 1 : 0;
        return v0;
    }

    private static int c1251(String property) { // line 1251
        int v0 = (property.startsWith("leastToughness")) ? 1 : 0;
        return v0;
    }

    private static int c1266(String property) { // line 1266
        int v0 = (property.startsWith("greatestCMC_")) ? 1 : 0;
        return v0;
    }

    private static int c1286(String property) { // line 1286
        int v0 = (property.startsWith("greatestRememberedCMC")) ? 1 : 0;
        return v0;
    }

    private static int c1303(String property) { // line 1303
        int v0 = (property.startsWith("lowestRememberedCMC")) ? 1 : 0;
        return v0;
    }

    private static int c1320(String property) { // line 1320
        int v0 = (property.startsWith("lowestCMC")) ? 1 : 0;
        return v0;
    }

    private static int c1326(String property) { // line 1326
        int v0 = (property.startsWith("enchanted")) ? 1 : 0;
        return v0;
    }

    private static int c1330(String property) { // line 1330
        int v0 = (property.startsWith("enchanting")) ? 1 : 0;
        return v0;
    }

    private static int c1334(String property) { // line 1334
        int v0 = (property.startsWith("equipped")) ? 1 : 0;
        return v0;
    }

    private static int c1338(String property) { // line 1338
        int v0 = (property.startsWith("equipping")) ? 1 : 0;
        return v0;
    }

    private static int c1342(String property) { // line 1342
        int v0 = (property.startsWith("modified")) ? 1 : 0;
        return v0;
    }

    private static int c1346(String property) { // line 1346
        int v0 = (property.startsWith("token")) ? 1 : 0;
        return v0;
    }

    private static int c1354(String property) { // line 1354
        int v0 = (property.startsWith("copiedSpell")) ? 1 : 0;
        return v0;
    }

    private static int c1358(String property) { // line 1358
        int v0 = (property.startsWith("hasXCost")) ? 1 : 0;
        return v0;
    }

    private static int c1363(String property) { // line 1363
        int v0 = (property.startsWith("suspended")) ? 1 : 0;
        return v0;
    }

    private static int c1367(String property) { // line 1367
        int v0 = (property.startsWith("delved")) ? 1 : 0;
        return v0;
    }

    private static int c1371(String property) { // line 1371
        int v0 = (property.startsWith("convoked")) ? 1 : 0;
        return v0;
    }

    private static int c1375(String property) { // line 1375
        int v0 = (property.startsWith("exploited")) ? 1 : 0;
        return v0;
    }

    private static int c1379(String property) { // line 1379
        int v0 = (property.startsWith("equalPT")) ? 1 : 0;
        return v0;
    }

    private static int c1383(String property) { // line 1383
        int v0 = (property.equals("powerGTtoughness")) ? 1 : 0;
        return v0;
    }

    private static int c1387(String property) { // line 1387
        int v0 = (property.equals("powerGTbasePower")) ? 1 : 0;
        return v0;
    }

    private static int c1391(String property) { // line 1391
        int v0 = (property.equals("powerNOTbasePower")) ? 1 : 0;
        return v0;
    }

    private static int c1395(String property) { // line 1395
        int v0 = (property.equals("powerLTtoughness")) ? 1 : 0;
        return v0;
    }

    private static int c1399(String property) { // line 1399
        int v0 = (property.equals("cmcEven")) ? 1 : 0;
        return v0;
    }

    private static int c1403(String property) { // line 1403
        int v0 = (property.equals("cmcOdd")) ? 1 : 0;
        return v0;
    }

    private static int c1407(String property) { // line 1407
        int v0 = (property.equals("powerEven")) ? 1 : 0;
        return v0;
    }

    private static int c1411(String property) { // line 1411
        int v0 = (property.equals("powerOdd")) ? 1 : 0;
        return v0;
    }

    private static int c1415(String property) { // line 1415
        int v0 = (property.equals("cmcChosenEvenOdd")) ? 1 : 0;
        return v0;
    }

    private static int c1423(String property) { // line 1423
        int v0 = (property.equals("cmcNotChosenEvenOdd")) ? 1 : 0;
        return v0;
    }

    private static int c1431(String property) { // line 1431
        int v8 = (property.startsWith("power")) ? 1 : 0;
        int v7 = v8 == 2 ? 2 : 1 - v8;
        int v6 = v7;
        if (v7 == 1) {
            int v10 = (property.startsWith("toughness")) ? 1 : 0;
            int v9 = v10 == 2 ? 2 : 1 - v10;
            v6 = v9;
        }
        int v5 = v6;
        if (v6 == 1) {
            int v12 = (property.startsWith("cmc")) ? 1 : 0;
            int v11 = v12 == 2 ? 2 : 1 - v12;
            v5 = v11;
        }
        int v4 = v5;
        if (v5 == 1) {
            int v14 = (property.startsWith("totalPT")) ? 1 : 0;
            int v13 = v14 == 2 ? 2 : 1 - v14;
            v4 = v13;
        }
        int v3 = v4;
        if (v4 == 1) {
            int v16 = (property.startsWith("numColors")) ? 1 : 0;
            int v15 = v16 == 2 ? 2 : 1 - v16;
            v3 = v15;
        }
        int v2 = v3;
        if (v3 == 1) {
            int v18 = (property.startsWith("basePower")) ? 1 : 0;
            int v17 = v18 == 2 ? 2 : 1 - v18;
            v2 = v17;
        }
        int v1 = v2;
        if (v2 == 1) {
            int v20 = (property.startsWith("baseToughness")) ? 1 : 0;
            int v19 = v20 == 2 ? 2 : 1 - v20;
            v1 = v19;
        }
        int v0 = v1;
        if (v1 == 1) {
            int v22 = (property.startsWith("numTypes")) ? 1 : 0;
            int v21 = v22 == 2 ? 2 : 1 - v22;
            v0 = v21;
        }
        return v0;
    }

    private static int c1432(String property) { // line 1432
        int v0 = (property.startsWith("ManaCost")) ? 1 : 0;
        return v0;
    }

    private static int c1441(String property) { // line 1441
        int v0 = (property.equals("HasCounters")) ? 1 : 0;
        return v0;
    }

    private static int c1445(String property) { // line 1445
        int v0 = (property.startsWith("counters")) ? 1 : 0;
        return v0;
    }

    private static int c1461(String property) { // line 1461
        int v0 = (property.startsWith("attacking")) ? 1 : 0;
        return v0;
    }

    private static int c1522(String property) { // line 1522
        int v0 = (property.startsWith("enlistedThisCombat")) ? 1 : 0;
        return v0;
    }

    private static int c1526(String property) { // line 1526
        int v0 = (property.startsWith("attackedThisCombat")) ? 1 : 0;
        return v0;
    }

    private static int c1537(String property) { // line 1537
        int v0 = (property.equals("blockedThisCombat")) ? 1 : 0;
        return v0;
    }

    private static int c1541(String property) { // line 1541
        int v0 = (property.equals("attackedBySourceThisCombat")) ? 1 : 0;
        return v0;
    }

    private static int c1550(String property) { // line 1550
        int v0 = (property.startsWith("blocking")) ? 1 : 0;
        return v0;
    }

    private static int c1583(String property) { // line 1583
        int v0 = (property.startsWith("sharesBlockingAssignmentWith")) ? 1 : 0;
        return v0;
    }

    private static int c1596(String property) { // line 1596
        int v0 = (property.equals("blocked")) ? 1 : 0;
        return v0;
    }

    private static int c1600(String property) { // line 1600
        int v0 = (property.startsWith("blockedBySourceThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1604(String property) { // line 1604
        int v0 = (property.startsWith("blockedBySourceLKI")) ? 1 : 0;
        return v0;
    }

    private static int c1608(String property) { // line 1608
        int v0 = (property.startsWith("blockedBySource")) ? 1 : 0;
        return v0;
    }

    private static int c1612(String property) { // line 1612
        int v0 = (property.startsWith("blockedThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1616(String property) { // line 1616
        int v0 = (property.startsWith("blockedByThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1620(String property) { // line 1620
        int v0 = (property.startsWith("blockedValidThisTurn ")) ? 1 : 0;
        return v0;
    }

    private static int c1640(String property) { // line 1640
        int v0 = (property.startsWith("blockedByValidThisTurn ")) ? 1 : 0;
        return v0;
    }

    private static int c1660(String property) { // line 1660
        int v0 = (property.startsWith("isBlockedByRemembered")) ? 1 : 0;
        return v0;
    }

    private static int c1674(String property) { // line 1674
        int v0 = (property.startsWith("blockedRemembered")) ? 1 : 0;
        return v0;
    }

    private static int c1687(String property) { // line 1687
        int v0 = (property.startsWith("blockedByRemembered")) ? 1 : 0;
        return v0;
    }

    private static int c1700(String property) { // line 1700
        int v0 = (property.startsWith("unblocked")) ? 1 : 0;
        return v0;
    }

    private static int c1704(String property) { // line 1704
        int v0 = (property.equals("attackersBandedWith")) ? 1 : 0;
        return v0;
    }

    private static int c1713(String property) { // line 1713
        int v0 = (property.equals("hadToAttackThisCombat")) ? 1 : 0;
        return v0;
    }

    private static int c1719(String property) { // line 1719
        int v0 = (property.equals("couldAttackButNotAttacking")) ? 1 : 0;
        return v0;
    }

    private static int c1727(String property) { // line 1727
        int v0 = (property.equals("linkedCastSA")) ? 1 : 0;
        return v0;
    }

    private static int c1735(String property) { // line 1735
        int v0 = (property.startsWith("kicked")) ? 1 : 0;
        return v0;
    }

    private static int c1755(String property) { // line 1755
        int v0 = (property.equals("bargained")) ? 1 : 0;
        return v0;
    }

    private static int c1767(String property) { // line 1767
        int v0 = (property.equals("surged")) ? 1 : 0;
        return v0;
    }

    private static int c1779(String property) { // line 1779
        int v0 = (property.equals("blitzed")) ? 1 : 0;
        return v0;
    }

    private static int c1791(String property) { // line 1791
        int v0 = (property.equals("dashed")) ? 1 : 0;
        return v0;
    }

    private static int c1803(String property) { // line 1803
        int v0 = (property.equals("escaped")) ? 1 : 0;
        return v0;
    }

    private static int c1811(String property) { // line 1811
        int v0 = (property.equals("evoked")) ? 1 : 0;
        return v0;
    }

    private static int c1823(String property) { // line 1823
        int v0 = (property.equals("PromisedGift")) ? 1 : 0;
        return v0;
    }

    private static int c1831(String property) { // line 1831
        int v0 = (property.equals("Teamwork")) ? 1 : 0;
        return v0;
    }

    private static int c1839(String property) { // line 1839
        int v0 = (property.equals("impended")) ? 1 : 0;
        return v0;
    }

    private static int c1851(String property) { // line 1851
        int v0 = (property.equals("prowled")) ? 1 : 0;
        return v0;
    }

    private static int c1863(String property) { // line 1863
        int v0 = (property.equals("spectacle")) ? 1 : 0;
        return v0;
    }

    private static int c1875(String property) { // line 1875
        int v0 = (property.equals("sneaked")) ? 1 : 0;
        return v0;
    }

    private static int c1887(String property) { // line 1887
        int v0 = (property.equals("foretold")) ? 1 : 0;
        return v0;
    }

    private static int c1891(String property) { // line 1891
        int v0 = (property.equals("warped")) ? 1 : 0;
        return v0;
    }

    private static int c1895(String property) { // line 1895
        int v0 = (property.equals("webSlinged")) ? 1 : 0;
        return v0;
    }

    private static int c1899(String property) { // line 1899
        int v0 = (property.equals("CrewedThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1903(String property) { // line 1903
        int v0 = (property.equals("CrewedBySourceThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1907(String property) { // line 1907
        int v0 = (property.equals("HasDevoured")) ? 1 : 0;
        return v0;
    }

    private static int c1911(String property) { // line 1911
        int v0 = (property.equals("harnessed")) ? 1 : 0;
        return v0;
    }

    private static int c1915(String property) { // line 1915
        int v0 = (property.equals("IsMonstrous")) ? 1 : 0;
        return v0;
    }

    private static int c1919(String property) { // line 1919
        int v0 = (property.equals("IsUnearthed")) ? 1 : 0;
        return v0;
    }

    private static int c1923(String property) { // line 1923
        int v0 = (property.equals("IsRenowned")) ? 1 : 0;
        return v0;
    }

    private static int c1927(String property) { // line 1927
        int v0 = (property.equals("IsSolved")) ? 1 : 0;
        return v0;
    }

    private static int c1931(String property) { // line 1931
        int v0 = (property.equals("IsSaddled")) ? 1 : 0;
        return v0;
    }

    private static int c1935(String property) { // line 1935
        int v0 = (property.equals("SaddledThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1939(String property) { // line 1939
        int v0 = (property.equals("VisitedThisTurn")) ? 1 : 0;
        return v0;
    }

    private static int c1943(String property) { // line 1943
        int v0 = (property.equals("IsSuspected")) ? 1 : 0;
        return v0;
    }

    private static int c1947(String property) { // line 1947
        int v0 = (property.equals("IsPrepared")) ? 1 : 0;
        return v0;
    }

    private static int c1951(String property) { // line 1951
        int v0 = (property.equals("IsRemembered")) ? 1 : 0;
        return v0;
    }

    private static int c1955(String property) { // line 1955
        int v0 = (property.equals("IsImprinted")) ? 1 : 0;
        return v0;
    }

    private static int c1959(String property) { // line 1959
        int v0 = (property.equals("IsGoaded")) ? 1 : 0;
        return v0;
    }

    private static int c1963(String property) { // line 1963
        int v0 = (property.equals("FullyUnlocked")) ? 1 : 0;
        return v0;
    }

    private static int c1967(String property) { // line 1967
        int v0 = (property.startsWith("canReceiveCounters")) ? 1 : 0;
        return v0;
    }

    private static int c1971(String property) { // line 1971
        int v0 = (property.equals("canBeTurnedFaceUp")) ? 1 : 0;
        return v0;
    }

    private static int c1975(String property) { // line 1975
        int v0 = (property.equals("canBeBeamedUp")) ? 1 : 0;
        return v0;
    }

    private static int c1979(String property) { // line 1979
        int v0 = (property.equals("NoAbilities")) ? 1 : 0;
        return v0;
    }

    private static int c1983(String property) { // line 1983
        int v0 = (property.equals("castKeyword")) ? 1 : 0;
        return v0;
    }

    private static int c1996(String property) { // line 1996
        int v0 = (property.equals("CastSaSource")) ? 1 : 0;
        return v0;
    }

    private static int c2005(String property) { // line 2005
        int v0 = (property.startsWith("CastSa")) ? 1 : 0;
        return v0;
    }

    private static int c2015(String property) { // line 2015
        int v0 = (property.startsWith("wasCastFrom")) ? 1 : 0;
        return v0;
    }

    private static int c2037(String property) { // line 2037
        int v0 = (property.startsWith("wasCast")) ? 1 : 0;
        return v0;
    }

    private static int c2045(String property) { // line 2045
        int v0 = (property.startsWith("set")) ? 1 : 0;
        return v0;
    }

    private static int c2055(String property) { // line 2055
        int v0 = (property.startsWith("inZone")) ? 1 : 0;
        return v0;
    }

    private static int c2062(String property) { // line 2062
        int v0 = (property.startsWith("inRealZone")) ? 1 : 0;
        return v0;
    }

    private static int c2068(String property) { // line 2068
        int v0 = (property.equals("IsCommander")) ? 1 : 0;
        return v0;
    }

    private static int c2073(String property) { // line 2073
        int v0 = (property.startsWith("NotedFor")) ? 1 : 0;
        return v0;
    }

    private static int c2089(String property) { // line 2089
        int v0 = (property.equals("NotedColor")) ? 1 : 0;
        return v0;
    }

    private static int c2098(String property) { // line 2098
        int v0 = (property.equals("NotedNameNobleBanneret")) ? 1 : 0;
        return v0;
    }

    private static int c2108(String property) { // line 2108
        int v0 = (property.equals("NotedNameAetherSearcher")) ? 1 : 0;
        return v0;
    }

    private static int c2118(String property) { // line 2118
        int v0 = (property.equals("NotedNameSmugglerCaptain")) ? 1 : 0;
        return v0;
    }

    private static int c2128(String property) { // line 2128
        int v0 = (property.equals("NotedGuessPhantasm")) ? 1 : 0;
        return v0;
    }

    private static int c2133(String property) { // line 2133
        int v0 = (property.equals("NotedTypes")) ? 1 : 0;
        return v0;
    }

    private static int c2145(String property) { // line 2145
        int v0 = (property.startsWith("Triggered")) ? 1 : 0;
        return v0;
    }

    private static int c2165(String property) { // line 2165
        int v0 = (property.startsWith("NotDefined")) ? 1 : 0;
        return v0;
    }

    private static int c2171(String property) { // line 2171
        int v0 = (property.equals("CanPayManaCost")) ? 1 : 0;
        return v0;
    }
}
